### ISSUE TITLE
Needed urgent help

### ISSUE THREAD

**Issue by PratheekXD** [TsunayoshiSawada/TsunayoshiSawada#1]
Sir I really need help please reply to me it's urgent

**Comment by TsunayoshiSawada** [comment]
Do why don't you reply with the problem?

**Comment by PratheekXD** [comment]
> Do why don't you reply with the problem?

Brother how do I deploy this in heroku 🥲 please help me

**Comment by TsunayoshiSawada** [comment]
> > Do why don't you reply with the problem?
> 
> Brother how do I deploy this in heroku 🥲 please help me

https://open.spotify.com/track/4NZrZgrRoR4GwR7flWOXRI?autoplay=true

**Comment by IndrajeethY** [comment]
Oh no

**Comment by Rohith-sreedharan** [comment]
Waah

**Comment by icebarf** [comment]
meme

**Comment by xgorn** [comment]
lol
